update deploy

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -139,14 +139,27 @@ jobs:
           ref: main
           path: IfricPlatform
           token: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
+
+      - name: List directory contents
+        run: ls -la IfricPlatform
+
       - id: build
         name: Build & Push Image
         shell: bash
         run: |
           export DOCKER_TAG="latest"
-          NIGHTLY_DOCKER_TAG=nightly-`date -I`-`date +%s`
+          NIGHTLY_DOCKER_TAG=nightly-$(date -I)-$(date +%s)
           docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
-          docker-compose build
+          
+          # Check for docker-compose.yml
+          if [ -f docker-compose.yml ]; then
+            echo "docker-compose.yml found, proceeding with build"
+            docker-compose build
+          else
+            echo "docker-compose.yml not found, exiting"
+            exit 1
+          fi
+          
           docker tag ${DOCKER_PREFIX}/ifric-platform-backend:${DOCKER_TAG} ${DOCKER_PREFIX}/ifric-platform-backend:${NIGHTLY_DOCKER_TAG}
           docker tag ${DOCKER_PREFIX}/ifric-platform-frontend:${DOCKER_TAG} ${DOCKER_PREFIX}/ifric-platform-frontend:${NIGHTLY_DOCKER_TAG}
           docker push ${DOCKER_PREFIX}/ifric-platform-backend:${DOCKER_TAG}
@@ -157,8 +170,8 @@ jobs:
           docker rmi ${DOCKER_PREFIX}/ifric-platform-backend:${NIGHTLY_DOCKER_TAG}
           docker rmi ${DOCKER_PREFIX}/ifric-platform-frontend:${DOCKER_TAG}
           docker rmi ${DOCKER_PREFIX}/ifric-platform-frontend:${NIGHTLY_DOCKER_TAG}
-          echo "NIGHTLY_DOCKER_TAG=${NIGHTLY_DOCKER_TAG}" >> "${GITHUB_OUTPUT}"           
-   clone-repo:
+          echo "NIGHTLY_DOCKER_TAG=${NIGHTLY_DOCKER_TAG}" >> "${GITHUB_OUTPUT}"         
+  clone-repo:
     runs-on: private-2
     steps:
       - uses: actions/checkout@v3
